version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=trainings_admin
      - POSTGRES_DB=trainings_tracker
    ports:
      - "5433:5432"
    volumes:
      - trainings_tracker_data:/var/lib/postgresql/data
      - src/main/resources/schema_init.sql:/docker-entrypoint-initdb.d/init.sql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080

volumes:
  trainings_tracker_data: 